// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: backend_api.proto
#ifndef GRPC_backend_5fapi_2eproto__INCLUDED
#define GRPC_backend_5fapi_2eproto__INCLUDED

#include "backend_api.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace backend {

class BackendService final {
 public:
  static constexpr char const* service_full_name() {
    return "backend.BackendService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 유저 관리
    virtual ::grpc::Status GetUser(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::backend::UserResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>> AsyncGetUser(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>>(AsyncGetUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>> PrepareAsyncGetUser(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>>(PrepareAsyncGetUserRaw(context, request, cq));
    }
    virtual ::grpc::Status AddUser(::grpc::ClientContext* context, const ::backend::NewUser& request, ::backend::UserResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>> AsyncAddUser(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>>(AsyncAddUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>> PrepareAsyncAddUser(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>>(PrepareAsyncAddUserRaw(context, request, cq));
    }
    // 점수 & 랭킹
    virtual ::grpc::Status UpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::backend::ScoreResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::ScoreResponse>> AsyncUpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::ScoreResponse>>(AsyncUpdateScoreRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::ScoreResponse>> PrepareAsyncUpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::ScoreResponse>>(PrepareAsyncUpdateScoreRaw(context, request, cq));
    }
    virtual ::grpc::Status GetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::backend::RankingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::RankingResponse>> AsyncGetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::RankingResponse>>(AsyncGetRankingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::RankingResponse>> PrepareAsyncGetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backend::RankingResponse>>(PrepareAsyncGetRankingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 유저 관리
      virtual void GetUser(::grpc::ClientContext* context, const ::backend::UserRequest* request, ::backend::UserResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUser(::grpc::ClientContext* context, const ::backend::UserRequest* request, ::backend::UserResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AddUser(::grpc::ClientContext* context, const ::backend::NewUser* request, ::backend::UserResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddUser(::grpc::ClientContext* context, const ::backend::NewUser* request, ::backend::UserResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 점수 & 랭킹
      virtual void UpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate* request, ::backend::ScoreResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate* request, ::backend::ScoreResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest* request, ::backend::RankingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest* request, ::backend::RankingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>* AsyncGetUserRaw(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>* PrepareAsyncGetUserRaw(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>* AsyncAddUserRaw(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::UserResponse>* PrepareAsyncAddUserRaw(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::ScoreResponse>* AsyncUpdateScoreRaw(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::ScoreResponse>* PrepareAsyncUpdateScoreRaw(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::RankingResponse>* AsyncGetRankingRaw(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backend::RankingResponse>* PrepareAsyncGetRankingRaw(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetUser(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::backend::UserResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>> AsyncGetUser(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>>(AsyncGetUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>> PrepareAsyncGetUser(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>>(PrepareAsyncGetUserRaw(context, request, cq));
    }
    ::grpc::Status AddUser(::grpc::ClientContext* context, const ::backend::NewUser& request, ::backend::UserResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>> AsyncAddUser(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>>(AsyncAddUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>> PrepareAsyncAddUser(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>>(PrepareAsyncAddUserRaw(context, request, cq));
    }
    ::grpc::Status UpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::backend::ScoreResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::ScoreResponse>> AsyncUpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::ScoreResponse>>(AsyncUpdateScoreRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::ScoreResponse>> PrepareAsyncUpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::ScoreResponse>>(PrepareAsyncUpdateScoreRaw(context, request, cq));
    }
    ::grpc::Status GetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::backend::RankingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::RankingResponse>> AsyncGetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::RankingResponse>>(AsyncGetRankingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::RankingResponse>> PrepareAsyncGetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backend::RankingResponse>>(PrepareAsyncGetRankingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUser(::grpc::ClientContext* context, const ::backend::UserRequest* request, ::backend::UserResponse* response, std::function<void(::grpc::Status)>) override;
      void GetUser(::grpc::ClientContext* context, const ::backend::UserRequest* request, ::backend::UserResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddUser(::grpc::ClientContext* context, const ::backend::NewUser* request, ::backend::UserResponse* response, std::function<void(::grpc::Status)>) override;
      void AddUser(::grpc::ClientContext* context, const ::backend::NewUser* request, ::backend::UserResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate* request, ::backend::ScoreResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateScore(::grpc::ClientContext* context, const ::backend::ScoreUpdate* request, ::backend::ScoreResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest* request, ::backend::RankingResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRanking(::grpc::ClientContext* context, const ::backend::RankingRequest* request, ::backend::RankingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>* AsyncGetUserRaw(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>* PrepareAsyncGetUserRaw(::grpc::ClientContext* context, const ::backend::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>* AsyncAddUserRaw(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::UserResponse>* PrepareAsyncAddUserRaw(::grpc::ClientContext* context, const ::backend::NewUser& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::ScoreResponse>* AsyncUpdateScoreRaw(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::ScoreResponse>* PrepareAsyncUpdateScoreRaw(::grpc::ClientContext* context, const ::backend::ScoreUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::RankingResponse>* AsyncGetRankingRaw(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backend::RankingResponse>* PrepareAsyncGetRankingRaw(::grpc::ClientContext* context, const ::backend::RankingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUser_;
    const ::grpc::internal::RpcMethod rpcmethod_AddUser_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateScore_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRanking_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 유저 관리
    virtual ::grpc::Status GetUser(::grpc::ServerContext* context, const ::backend::UserRequest* request, ::backend::UserResponse* response);
    virtual ::grpc::Status AddUser(::grpc::ServerContext* context, const ::backend::NewUser* request, ::backend::UserResponse* response);
    // 점수 & 랭킹
    virtual ::grpc::Status UpdateScore(::grpc::ServerContext* context, const ::backend::ScoreUpdate* request, ::backend::ScoreResponse* response);
    virtual ::grpc::Status GetRanking(::grpc::ServerContext* context, const ::backend::RankingRequest* request, ::backend::RankingResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUser(::grpc::ServerContext* context, ::backend::UserRequest* request, ::grpc::ServerAsyncResponseWriter< ::backend::UserResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddUser() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddUser(::grpc::ServerContext* context, ::backend::NewUser* request, ::grpc::ServerAsyncResponseWriter< ::backend::UserResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateScore() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_UpdateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateScore(::grpc::ServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateScore(::grpc::ServerContext* context, ::backend::ScoreUpdate* request, ::grpc::ServerAsyncResponseWriter< ::backend::ScoreResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRanking : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRanking() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetRanking() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRanking(::grpc::ServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRanking(::grpc::ServerContext* context, ::backend::RankingRequest* request, ::grpc::ServerAsyncResponseWriter< ::backend::RankingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUser<WithAsyncMethod_AddUser<WithAsyncMethod_UpdateScore<WithAsyncMethod_GetRanking<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::backend::UserRequest, ::backend::UserResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backend::UserRequest* request, ::backend::UserResponse* response) { return this->GetUser(context, request, response); }));}
    void SetMessageAllocatorFor_GetUser(
        ::grpc::MessageAllocator< ::backend::UserRequest, ::backend::UserResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backend::UserRequest, ::backend::UserResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUser(
      ::grpc::CallbackServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddUser() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::backend::NewUser, ::backend::UserResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backend::NewUser* request, ::backend::UserResponse* response) { return this->AddUser(context, request, response); }));}
    void SetMessageAllocatorFor_AddUser(
        ::grpc::MessageAllocator< ::backend::NewUser, ::backend::UserResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backend::NewUser, ::backend::UserResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddUser(
      ::grpc::CallbackServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateScore() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::backend::ScoreUpdate, ::backend::ScoreResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backend::ScoreUpdate* request, ::backend::ScoreResponse* response) { return this->UpdateScore(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateScore(
        ::grpc::MessageAllocator< ::backend::ScoreUpdate, ::backend::ScoreResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backend::ScoreUpdate, ::backend::ScoreResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateScore(::grpc::ServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateScore(
      ::grpc::CallbackServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRanking : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRanking() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::backend::RankingRequest, ::backend::RankingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backend::RankingRequest* request, ::backend::RankingResponse* response) { return this->GetRanking(context, request, response); }));}
    void SetMessageAllocatorFor_GetRanking(
        ::grpc::MessageAllocator< ::backend::RankingRequest, ::backend::RankingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backend::RankingRequest, ::backend::RankingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRanking() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRanking(::grpc::ServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRanking(
      ::grpc::CallbackServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUser<WithCallbackMethod_AddUser<WithCallbackMethod_UpdateScore<WithCallbackMethod_GetRanking<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddUser() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateScore() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_UpdateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateScore(::grpc::ServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRanking : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRanking() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetRanking() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRanking(::grpc::ServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddUser() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateScore() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_UpdateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateScore(::grpc::ServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateScore(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRanking : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRanking() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetRanking() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRanking(::grpc::ServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRanking(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddUser() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateScore() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateScore(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateScore(::grpc::ServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateScore(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRanking : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRanking() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRanking(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRanking() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRanking(::grpc::ServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRanking(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backend::UserRequest, ::backend::UserResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backend::UserRequest, ::backend::UserResponse>* streamer) {
                       return this->StreamedGetUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::backend::UserRequest* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backend::UserRequest,::backend::UserResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddUser() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backend::NewUser, ::backend::UserResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backend::NewUser, ::backend::UserResponse>* streamer) {
                       return this->StreamedAddUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::backend::NewUser* /*request*/, ::backend::UserResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backend::NewUser,::backend::UserResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateScore() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backend::ScoreUpdate, ::backend::ScoreResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backend::ScoreUpdate, ::backend::ScoreResponse>* streamer) {
                       return this->StreamedUpdateScore(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateScore(::grpc::ServerContext* /*context*/, const ::backend::ScoreUpdate* /*request*/, ::backend::ScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateScore(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backend::ScoreUpdate,::backend::ScoreResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRanking : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRanking() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backend::RankingRequest, ::backend::RankingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backend::RankingRequest, ::backend::RankingResponse>* streamer) {
                       return this->StreamedGetRanking(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRanking() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRanking(::grpc::ServerContext* /*context*/, const ::backend::RankingRequest* /*request*/, ::backend::RankingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRanking(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backend::RankingRequest,::backend::RankingResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUser<WithStreamedUnaryMethod_AddUser<WithStreamedUnaryMethod_UpdateScore<WithStreamedUnaryMethod_GetRanking<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUser<WithStreamedUnaryMethod_AddUser<WithStreamedUnaryMethod_UpdateScore<WithStreamedUnaryMethod_GetRanking<Service > > > > StreamedService;
};

}  // namespace backend


#endif  // GRPC_backend_5fapi_2eproto__INCLUDED
